#!/bin/bash

#Kommentaar siia kirjutame
#see skript trykib välja kasutaja_ninmi ja asukoht
#muutujale ipa omistame oma IPa-s
ipa=`hostname -I`

echo -n "Sinu kasutaja nimi on: "
whoami
sleep 1.5
echo -n "Sinu praegune kataloog on: "
pwd
sleep 0.5
echo -n "Sinu arvuti ip aadress on: $ipa"

